from typing import Any, Dict, List
from ..models.schema import ScenarioDefinition

SCENARIOS: List[ScenarioDefinition] = [
    ScenarioDefinition(
        id="scenario_1_success",
        title="Scenario 1: Approved Zelar Vendor Settlement (Success)",
        description="Thoughtworks executes vendor payout of ₹2,40,000 to vendor Zelar for verified invoice ZELAR-MAR-2026-104. Fully approved, verified bank destination ba_zelar_corp_hdfc_0981, automated multi-system reconciliation.",
        prompt="Handle the Zelar payment.",
        expected_outcome="All 5 providers participate: Notion verifies invoice & bank destination, Stripe checks history, Slack confirms no holds, Jira links SCRUM-42, Human approves ₹2.4L with locked payload, Payout executes via stripe.payout.create, Jira updated, Gmail remittance sent, Slack notified, Notion recorded.",
        difficulty="Standard",
        tags=["Vendor-Settlement", "Payout", "Multi-System", "Human-Gate"],
    ),
    ScenarioDefinition(
        id="scenario_2_failure",
        title="Scenario 2: Vendor Payout Failure (Exception Engine)",
        description="Zelar vendor settlement is approved and locked, but payout fails with 'could_not_process / destination_bank_error'. OpsPilot diagnoses failure, updates Jira, alerts Finance in Slack, and records exception without terminating blindly.",
        prompt="Handle the Zelar payment.",
        expected_outcome="Diagnoses failure as operational exception. Escalates to Jira (SCRUM-42), alerts #finance-ops in Slack, updates Notion with FAILED state and recovery steps.",
        difficulty="Advanced Exception",
        tags=["Exception-Handling", "Payout-Decline", "Jira-Escalation", "Slack-Alert"],
    ),
    ScenarioDefinition(
        id="scenario_3_unknown_timeout",
        title="Scenario 3: Payout Timeout / Unknown State Recovery",
        description="Payout request times out mid-transaction. OpsPilot distinguishes UNKNOWN from FAILED, prevents duplicate payout creation attempt, queries Stripe using stripe.payout.get, and reconciles state safely without blind retry.",
        prompt="Handle the Zelar payment.",
        expected_outcome="Detects UNKNOWN state, avoids duplicate payout creation, queries Stripe via stripe.payout.get for known payout ID, confirms final status, and resolves reconciliation safely.",
        difficulty="Expert Recovery",
        tags=["Timeout", "Idempotency", "Unknown-State", "Duplicate-Prevention"],
    ),
    ScenarioDefinition(
        id="scenario_4_mismatch",
        title="Scenario 4: Invoice Amount Mismatch Discrepancy",
        description="User requests payout of ₹2,80,000, but Notion invoice records show approved amount of ₹2,40,000. OpsPilot detects discrepancy, blocks payout before creation, logs audit, and creates Jira reconciliation task.",
        prompt="Pay ₹2,80,000 to vendor Zelar for March infrastructure services.",
        expected_outcome="Blocks unauthorized amount variance (₹40,000 mismatch), creates Jira reconciliation issue, notifies Finance via Slack, does not prompt for payout approval.",
        difficulty="Safety & Compliance",
        tags=["Discrepancy", "Fraud-Prevention", "Safety-Block", "Audit"],
    ),
]

# Scenario-specific mock data bundles (strictly mirroring Swytchcode schemas)
MOCK_DATA = {
    "zelar_vendor_profile": {
        "vendor_name": "Zelar",
        "legal_name": "Zelar Technologies Private Limited",
        "vendor_id": "VEND-ZELAR-009",
        "tax_id": "GSTIN29AAACZ1234F1Z5",
        "category": "Cloud Infrastructure & DevOps Professional Services",
        "contact_email": "billing@zelar.io",
        "primary_contact": "Arun Kumar, Head of Accounts",
        "stripe_customer_id": "cus_ZelarTech_99812",
        "verified_payout_destination": "ba_zelar_corp_hdfc_0981",
        "bank_account_verified": True,
        "bank_name": "HDFC Bank Ltd",
        "account_last4": "0981",
        "payment_terms": "Net-30",
        "currency": "INR",
        "status": "ACTIVE_VERIFIED",
    },
    "zelar_invoice": {
        "invoice_number": "ZELAR-MAR-2026-104",
        "issue_date": "2026-03-15",
        "due_date": "2026-04-15",
        "amount": 240000.00,
        "currency": "INR",
        "formatted_amount": "₹2,40,000.00",
        "description": "March 2026 Cloud Infrastructure & DevOps Managed Services",
        "line_items": [
            {"item": "Kubernetes Cluster Fleet Management", "hours": 80, "rate": 1500, "total": 120000.00},
            {"item": "CI/CD Pipeline Security Hardening & Observability", "hours": 60, "rate": 1500, "total": 90000.00},
            {"item": "AWS Cloud Optimization & FinOps Support", "hours": 20, "rate": 1500, "total": 30000.00},
        ],
        "po_number": "PO-TW-2026-0881",
        "approval_status": "APPROVED_BY_FINANCE",
        "approver": "Rohan Deshmukh (Finance Director)",
        "approved_at": "2026-03-20T10:15:00Z",
    },
    "stripe_records": {
        "customer": {
            "id": "cus_ZelarTech_99812",
            "object": "customer",
            "name": "Zelar Technologies Private Limited",
            "email": "billing@zelar.io",
            "currency": "inr",
            "balance": 0,
            "delinquent": False,
            "created": 1742000000,
            "livemode": True,
            "metadata": {
                "enterprise_client": "Thoughtworks",
                "vendor_id": "VEND-ZELAR-009",
                "verified_destination": "ba_zelar_corp_hdfc_0981",
            },
        },
        "payment_intents_history": [
            {
                "id": "po_zelar_feb2026_01",
                "object": "payout",
                "amount": 21000000,  # 210,000 INR in paise
                "currency": "inr",
                "status": "paid",
                "destination": "ba_zelar_corp_hdfc_0981",
                "description": "February 2026 Cloud Services - Invoice ZELAR-FEB-2026-089",
                "created": 1739500000,
            }
        ],
        "payout_success": {
            "id": "po_zelar_mar2026_succ104",
            "object": "payout",
            "amount": 24000000,
            "currency": "inr",
            "destination": "ba_zelar_corp_hdfc_0981",
            "status": "paid",
            "arrival_date": 1742468000,
            "method": "standard",
            "description": "Vendor Settlement: ZELAR-MAR-2026-104 (Thoughtworks AP)",
            "created": 1742467200,
            "metadata": {
                "opspilot_operation_id": "op_zelar_20260326_104",
                "vendor_id": "VEND-ZELAR-009",
                "po_id": "PO-TW-2026-0881",
                "invoice_id": "ZELAR-MAR-2026-104",
            },
        },
        "payout_failed": {
            "id": "po_zelar_mar2026_fail99",
            "object": "payout",
            "amount": 24000000,
            "currency": "inr",
            "destination": "ba_zelar_corp_hdfc_0981",
            "status": "failed",
            "failure_code": "could_not_process",
            "failure_message": "The destination bank account could not accept the payout at this time.",
            "arrival_date": 1742468000,
            "method": "standard",
            "created": 1742467200,
            "metadata": {
                "opspilot_operation_id": "op_zelar_20260326_104",
                "vendor_id": "VEND-ZELAR-009",
                "po_id": "PO-TW-2026-0881",
                "invoice_id": "ZELAR-MAR-2026-104",
            },
        },
        "payout_pending_recon": {
            "id": "po_zelar_mar2026_timeout_recon",
            "object": "payout",
            "amount": 24000000,
            "currency": "inr",
            "destination": "ba_zelar_corp_hdfc_0981",
            "status": "in_transit",
            "arrival_date": 1742468000,
            "method": "standard",
            "created": 1742467200,
            "metadata": {
                "opspilot_operation_id": "op_zelar_20260326_104",
                "vendor_id": "VEND-ZELAR-009",
                "po_id": "PO-TW-2026-0881",
                "invoice_id": "ZELAR-MAR-2026-104",
            },
        },
    },
    "slack_finance_discussion": {
        "channel": "#finance-ops",
        "channel_id": "C089FINOPS",
        "messages": [
            {
                "user": "rohan.deshmukh",
                "text": "Approved invoice ZELAR-MAR-2026-104 for ₹2,40,000. DevOps confirmed all milestones delivered. Greenlight for vendor settlement.",
                "ts": "1742465700.001200",
            },
            {
                "user": "priya.nair",
                "text": "Acknowledged. Verified destination account ba_zelar_corp_hdfc_0981. No payment holds on vendor Zelar. Scheduled for payout.",
                "ts": "1742466000.001500",
            },
        ],
    },
    "jira_incident": {
        "key": "SCRUM-42",
        "id": "10042",
        "summary": "Process Vendor Settlement: Zelar (Invoice ZELAR-MAR-2026-104)",
        "description": "Task tracking vendor settlement verification, human authorization gate, and payout for Zelar March infrastructure services.",
        "status": "In Progress",
        "issue_type": "Vendor Settlement Task",
        "priority": "High",
        "assignee": "OpsPilot AI Operator",
        "reporter": "rohan.deshmukh",
        "labels": ["vendor-settlement", "payout", "zelar", "finance-ops", "infrastructure"],
    },
    "gmail_threads": [
        {
            "id": "thread_zelar_inv_104",
            "snippet": "Invoice ZELAR-MAR-2026-104 attached for March DevOps & Cloud infrastructure services.",
            "from": "Arun Kumar <billing@zelar.io>",
            "to": "accounts-payable@thoughtworks.com",
            "subject": "Invoice ZELAR-MAR-2026-104 - Zelar Technologies",
            "date": "Sat, 15 Mar 2026 09:30:00 +0530",
        }
    ],
}
